[phases.setup]
nixPkgs = ['php83', 'php83Packages.composer', 'php83Extensions.mbstring', 'php83Extensions.xml', 'php83Extensions.tokenizer', 'php83Extensions.pdo', 'php83Extensions.pdo_mysql', 'php83Extensions.curl', 'php83Extensions.fileinfo', 'php83Extensions.openssl', 'php83Extensions.bcmath', 'php83Extensions.ctype', 'nodejs_18', 'npm-9_x']

[phases.install]
cmds = ['composer install --no-dev --ignore-platform-reqs', 'npm ci']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT'
